version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 100
  method-complexity:
    enabled: true
    config:
      threshold: 20
plugins:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_paths:
  - "__test__/"
  - "dist/data/initial_dic.json"
  - "dist/options/milligram.min.css"
